import streamlit as st
import pandas as pd
import numpy as np
import time

st.set_page_config(page_title="Drift Monitor", page_icon="📉", layout="wide")
st.title("📉 Data Drift Detection")
st.markdown("Monitoring data distribution shifts in production vs. reference data.")


# Mock data to simulate an Evidently AI report
st.info("💡 **Note**: In a production environment, this page embeds HTML reports generated by **Evidently AI** (saved during inference logging).")

st.markdown("---")

col1, col2 = st.columns(2)

with col1:
    st.markdown("### 📊 Dataset Drift Summary")
    
    st.metric("Drifted Features", "2 / 55", "3.6%")
    st.progress(0.036, text="Dataset Drift Score: 0.036 (Threshold: 0.5)")
    st.success("✅ No significant dataset drift detected.")

with col2:
    st.markdown("### 🎯 Target Drift Summary")
    
    st.metric("Churn Rate Change", "26.5% → 28.1%", "+1.6%")
    st.progress(0.12, text="Target Distribution Drift Score: 0.12 (Threshold: 0.2)")
    st.success("✅ Target distribution remains stable.")

st.markdown("---")
st.markdown("### Feature Distribution Shifts")

st.markdown("Below are continuous numerical feature distributions compared to the reference dataset.")

import altair as alt

# Mock distribution data
np.random.seed(42)
ref_data = np.random.normal(loc=65, scale=30, size=1000)
prod_data = np.random.normal(loc=68, scale=32, size=500)

df_ref = pd.DataFrame({"Monthly Charges": ref_data, "Source": "Reference Data"})
df_prod = pd.DataFrame({"Monthly Charges": prod_data, "Source": "Production Data"})
df_dist = pd.concat([df_ref, df_prod])

# Provide valid bin extents to avoid VegaLite warning
chart = alt.Chart(df_dist).mark_bar(opacity=0.7).encode(
    alt.X('Monthly Charges:Q', bin=alt.Bin(maxbins=50, extent=[0, 150]), title='Monthly Charges'),
    alt.Y('count()', stack=None, title='Count'),
    alt.Color('Source:N', scale=alt.Scale(range=['#3b82f6', '#ef4444']))
).properties(height=300)

st.altair_chart(chart, use_container_width=True)

st.warning("⚠️ **Feature Warning: 'tenure'** - Showing a slight drift (score: 0.15), new customers seem to be churning slightly earlier. Monitor closely.")
